import type { Hotel } from "@/lib/data";
import { imagePool } from "@/lib/hotels/images";

export const kaohsiungHotels: Hotel[] = [
{
    id: "kh-01",
    name: "橘屋毛孩旅宿",
    slug: "orange-paws-kaohsiung",
    city: { name: "高雄", slug: "kaohsiung" },
    district: "左營區",
    address: "高雄市左營區文自路 18 號",
    phone: "07-345-1818",
    lineId: "@orange-paws",
    bookingUrl: "tel:07-345-1818",
    shareUrl: "https://maohai-stay-guide.example.com/hotels/orange-paws-kaohsiung",
    websiteUrl: "https://example.com/orange-paws",
    googleMapUrl: "https://www.google.com/maps?q=高雄市左營區文自路18號&output=embed",
    description: "鄰近高鐵與捷運，提供獨立房型、全天候攝影機與每日散步回報。適合第一次外宿或需要穩定作息的狗狗。",
    priceMin: 900,
    priceMax: 1800,
    rating: 4.8,
    isFeatured: true,
    petTypes: ["狗", "貓"],
    sizeLimits: ["小型犬", "中型犬"],
    services: ["寵物住宿", "寵物安親", "24小時監視器", "接送服務"],
    hasCctv: true,
    hasPickupService: true,
    tags: ["近高鐵", "每日照片回報", "獨立套房"],
    hours: "週一至週日 09:00-21:00",
    images: imagePool.slice(0, 3).map((url, index) => ({ url, alt: `橘屋毛孩旅宿照片 ${index + 1}` }))
  },
  {
    id: "kh-02",
    name: "河堤寵物安親館",
    slug: "riverside-pet-care",
    city: { name: "高雄", slug: "kaohsiung" },
    district: "三民區",
    address: "高雄市三民區明哲路 68 號",
    phone: "07-395-2020",
    lineId: "@riversidepet",
    googleMapUrl: "https://www.google.com/maps?q=高雄市三民區明哲路68號&output=embed",
    description: "主打白天安親與短期住宿，室內遊戲區採防滑地墊，照護人員會依毛孩個性安排活動時間。",
    priceMin: 650,
    priceMax: 1500,
    rating: 4.6,
    isFeatured: true,
    petTypes: ["狗"],
    sizeLimits: ["小型犬", "中型犬", "大型犬"],
    services: ["寵物住宿", "寵物安親", "接送服務"],
    hasPickupService: true,
    tags: ["防滑地墊", "分區活動", "短住友善"],
    hours: "週一至週六 08:30-20:30",
    images: [imagePool[1], imagePool[3], imagePool[0]].map((url, index) => ({ url, alt: `河堤寵物安親館照片 ${index + 1}` }))
  },
  {
    id: "kh-03",
    name: "森呼吸貓狗旅店",
    slug: "forest-breathe-pet-hotel",
    city: { name: "高雄", slug: "kaohsiung" },
    district: "鳳山區",
    address: "高雄市鳳山區青年路二段 120 號",
    phone: "07-777-6120",
    lineId: "@forestpet",
    googleMapUrl: "https://www.google.com/maps?q=高雄市鳳山區青年路二段120號&output=embed",
    description: "貓狗分層照護，附設美容服務與空氣清淨設備，適合需要美容加住宿的一站式需求。",
    priceMin: 800,
    priceMax: 2000,
    rating: 4.7,
    isFeatured: false,
    petTypes: ["狗", "貓"],
    sizeLimits: ["小型犬", "中型犬"],
    services: ["寵物住宿", "寵物美容", "24小時監視器"],
    hasCctv: true,
    tags: ["貓狗分層", "美容加購", "空氣清淨"],
    hours: "週二至週日 10:00-20:00",
    images: [imagePool[4], imagePool[2], imagePool[3]].map((url, index) => ({ url, alt: `森呼吸貓狗旅店照片 ${index + 1}` }))
  },
  {
    id: "kh-04",
    name: "Luca寵物旅宿",
    slug: "luca-petstay-kaohsiung",
    city: { name: "高雄", slug: "kaohsiung" },
    district: "前金區",
    address: "高雄市前金區成功一路 352 號",
    phone: "0916-809-181",
    websiteUrl: "https://www.instagram.com/luca_petstay/",
    instagramUrl: "https://www.instagram.com/luca_petstay/",
    googleMapUrl: "https://www.google.com/maps?q=高雄市前金區成功一路352號&output=embed",
    description: "提供狗狗住宿服務，依體重區間安排住宿價格，特殊需求服務會依實際照護內容另行加價。",
    priceDetails: [
      "狗狗住宿價格",
      "1-7kg NT$ 500 / 晚",
      "7-14kg NT$ 800 / 晚",
      "14-21kg NT$ 1,200 / 晚",
      "21kg 以上 NT$ 1,600 / 晚",
      "特殊需求服務加價 NT$ 50-100 不等"
    ],
    priceMin: 500,
    priceMax: 1600,
    rating: 5,
    isFeatured: false,
    petTypes: ["狗"],
    sizeLimits: ["小型犬", "中型犬", "大型犬"],
    services: ["寵物住宿"],
    tags: ["狗狗住宿", "體重分級價格", "前金區"],
    highlights: ["體重分級住宿價格", "前金區可聯絡官方 Instagram", "可接待大型犬"],
    sourceUrl: "https://www.instagram.com/luca_petstay/",
    lastUpdated: "2026-05-21",
    hours: "請洽店家確認",
    images: [imagePool[1], imagePool[0], imagePool[2]].map((url, index) => ({ url, alt: `Luca寵物旅宿照片 ${index + 1}` }))
  },
  {
    id: "kh-05",
    name: "妮蘿毛孩沙龍旅店",
    slug: "niro-pet-salon-hotel",
    city: { name: "高雄", slug: "kaohsiung" },
    district: "前鎮區",
    address: "806高雄市前鎮區振興里文林街 43 號",
    phone: "0978-829-128",
    lineId: "@797cxdrc",
    facebookUrl: "https://www.facebook.com/p/%E5%A6%AE%E8%98%BF%E6%AF%9B%E5%AD%A9%E6%B2%99%E9%BE%8D%E6%97%85%E5%BA%97-61563294481634/",
    instagramUrl: "https://www.instagram.com/niropet.hotel",
    googleMapUrl: "https://www.google.com/maps?q=妮蘿毛孩沙龍旅店&output=embed",
    description: "提供寵物住宿、美容與安親服務，重視毛孩在寄宿與整理過程中的舒適感，讓飼主可透過 LINE 先確認照護需求。",
    priceDetails: [
      "狗狗住宿價格",
      "5kg 以下 NT$ 550 / 晚",
      "6-12kg NT$ 650 / 晚",
      "13-20kg NT$ 800 / 晚",
      "21kg 以上 NT$ 2,100 / 晚"
    ],
    stayRulesUrl: "https://www.facebook.com/photo?fbid=122210904380443149&set=pcb.122210906666443149",
    priceMin: 550,
    priceMax: 2100,
    rating: 5,
    isFeatured: false,
    petTypes: ["狗", "貓"],
    sizeLimits: ["請洽店家"],
    services: ["寵物住宿", "寵物安親", "寵物美容"],
    tags: ["美容服務", "寵物安親", "前鎮區"],
    highlights: ["住宿、美容與安親資訊集中", "LINE 可先確認入住需求", "提供社群聯絡入口"],
    sourceUrl: "https://www.facebook.com/p/%E5%A6%AE%E8%98%BF%E6%AF%9B%E5%AD%A9%E6%B2%99%E9%BE%8D%E6%97%85%E5%BA%97-61563294481634/",
    lastUpdated: "2026-05-22",
    hours: "週一 10:00-18:00、週二休息、週三至週日 10:00-18:00",
    images: [imagePool[3], imagePool[0], imagePool[4]].map((url, index) => ({ url, alt: `妮蘿毛孩沙龍旅店照片 ${index + 1}` }))
  },
  {
    id: "kh-06",
    name: "毛絨絨澡堂x貓茸茸旅館",
    slug: "pet-bathing-cat-hotel",
    city: { name: "高雄", slug: "kaohsiung" },
    district: "前鎮區",
    address: "806高雄市前鎮區忠孝里民權二路 613 號",
    phone: "07-330-0313",
    lineId: "monono_613",
    lineUrl: "https://line.me/ti/p/4S_Xqz8btq",
    websiteUrl: "https://www.pet-bathing.com.tw/",
    googleMapUrl: "https://www.google.com/maps?q=806高雄市前鎮區民權二路613號&output=embed",
    description: "提供寵物美容、住宿與安親服務，毛絨絨澡堂以陪伴與舒適照護為核心，貓茸茸旅館另設貓咪住宿空間，適合先透過 LINE 或電話確認美容與住宿安排。",
    priceMin: 0,
    priceMax: 0,
    priceLabel: "請洽店家",
    isFeatured: false,
    petTypes: ["狗", "貓"],
    sizeLimits: ["請洽店家"],
    services: ["寵物住宿", "寵物安親", "寵物美容"],
    tags: ["貓咪住宿", "美容服務", "前鎮區"],
    highlights: ["貓咪住宿與美容服務", "官方網站可確認服務內容", "可透過 LINE 或電話詢問"],
    sourceUrl: "https://www.pet-bathing.com.tw/",
    lastUpdated: "2026-05-21",
    hours: "週一至週日 10:00-19:00",
    images: [imagePool[4], imagePool[1], imagePool[0]].map((url, index) => ({ url, alt: `毛絨絨澡堂x貓茸茸旅館照片 ${index + 1}` }))
  },
  {
    id: "kh-07",
    name: "痴心人貓舍",
    slug: "infatuated-cat-hotel",
    city: { name: "高雄", slug: "kaohsiung" },
    district: "苓雅區",
    address: "802高雄市苓雅區三多二路 227 號",
    phone: "0981-285-159",
    lineId: "@857oepiz",
    lineUrl: "https://line.me/R/ti/p/@857oepiz?ts=12291926&oat_content=url",
    websiteUrl: "https://www.infatuated1985.com/",
    facebookUrl: "https://www.facebook.com/profile.php?id=100087887208995",
    instagramUrl: "https://www.instagram.com/a0926680789/",
    googleMapUrl: "https://www.google.com/maps?q=802高雄市苓雅區三多二路227號&output=embed",
    description: "位於高雄苓雅區的貓咪住宿資訊入口，提供商務、豪華與 VIP 房型價格級距，也可透過官方網站、社群與 LINE 確認入住規則與照護安排。",
    priceDetails: [
      "住宿價格",
      "商務房型（小）平日 NT$ 450 / 日、假日 NT$ 500 / 日",
      "商務房型（大）平日 NT$ 550 / 日、假日 NT$ 600 / 日",
      "豪華房型 平日 NT$ 750 / 日、假日 NT$ 850 / 日",
      "VIP 房型 平日 NT$ 1,300 / 日、假日 NT$ 1,400 / 日"
    ],
    priceMin: 450,
    priceMax: 1400,
    isFeatured: false,
    petTypes: ["貓"],
    acceptsCat: true,
    sizeLimits: ["貓咪住宿"],
    services: ["寵物住宿"],
    tags: ["貓咪住宿", "貓舍", "苓雅區"],
    highlights: ["苓雅區貓咪住宿資訊", "可透過官方網站與 LINE 詢問", "提供 Instagram 與 Facebook 聯絡入口"],
    sourceUrl: "https://www.infatuated1985.com/",
    lastUpdated: "2026-05-22",
    hours: "週一至週日 11:00-20:00",
    images: [imagePool[4], imagePool[3], imagePool[0]].map((url, index) => ({ url, alt: `痴心人貓舍照片 ${index + 1}` }))
  },
  {
    id: "kh-08",
    name: "熊大心寵物精品旅館",
    slug: "line-me",
    city: {
      name: "高雄",
      slug: "kaohsiung"
    },
    district: "鼓山區",
    address: "804高雄市鼓山區興宗里鼓山二路110號",
    phone: "07 551 6688",
    lineUrl: "https://line.me/ti/p/R6BGN9AefE",
    facebookUrl: "https://www.facebook.com/SDSpethotel/",
    googleMapUrl: "https://www.google.com/maps?q=804%E9%AB%98%E9%9B%84%E5%B8%82%E9%BC%93%E5%B1%B1%E5%8D%80%E8%88%88%E5%AE%97%E9%87%8C%E9%BC%93%E5%B1%B1%E4%BA%8C%E8%B7%AF110%E8%99%9F&output=embed",
    description: "熊大心寵物精品旅館位於高雄鼓山區，目前已整理 Google Maps 上的地址、電話、營業時間與官方連結。實際住宿價格、可接待寵物與入住規則，建議預約前再向店家確認。",
    highlights: [
      "Google Maps 基本資料已匯入",
      "住宿公約已整理",
      "提供美容服務注意事項"
    ],
    notices: [
      "住宿營業時間為 10:00-19:00；第一次入住建議 18:30 前抵達，需交接毛孩入住注意事項，第二次住宿可於 19:00 前到。",
      "如退宿當日無洗澡且超過入住時間，會收取安親費用；狗狗以每小時 NT$60-150 計，貓咪每小時 NT$200 起，同房兩隻另計。如有洗澡則不需負擔安親費。",
      "最晚退宿時間為 19:00，逾時不候。",
      "美容洗澡包含剪指甲、剃腳底毛、剃肛門毛、肚子毛、清耳朵、拔耳毛、擠肛門腺、修腳圓與修眼角；如需修整個頭請提前告知，會酌收修頭費用 NT$100 起。",
      "美容額外項目包含刷牙 NT$50 起、剪指甲 NT$50 起、拆結費 NT$100 起、修頭 NT$100 起。",
      "美容前請主動告知毛孩是否有特殊病史；洗澡者請於 16:30-17:00 前入館，大修剪、毛球與剪毛者請於 16:00 前入館。",
      "有打疫苗的毛孩需一個禮拜後才能洗澡，避免免疫力下降造成容易感冒或生病。",
      "身上有攜帶跳蚤、壁蝨者，會另外收取除蚤與環境清潔費 NT$100 起；毛孩若攻擊美容師，會另外酌收手折修費 NT$100 起。"
    ],
    reviewCount: 58,
    sourceUrl: "https://line.me/ti/p/R6BGN9AefE",
    lastUpdated: "2026-07-30",
    priceMin: 0,
    priceMax: 0,
    priceLabel: "請洽店家",
    rating: 4.3,
    isFeatured: false,
    petTypes: [],
    sizeLimits: [
      "請洽店家"
    ],
    services: [
      "寵物住宿",
      "寵物美容"
    ],
    tags: [
      "鼓山區"
    ],
    hours: "星期一: 10:00 – 19:00、星期二: 10:00 – 19:00、星期三: 10:00 – 19:00、星期四: 10:00 – 19:00、星期五: 10:00 – 19:00、星期六: 10:00 – 19:00、星期日: 10:00 – 19:00",
    images: [imagePool[0], imagePool[1], imagePool[2]].map((url, index) => ({ url, alt: `熊大心寵物精品旅館照片 ${index + 1}` }))
  },
];
