import type { Hotel } from "@/lib/data";
import { imagePool } from "@/lib/hotels/images";

export const tainanHotels: Hotel[] = [
{
    id: "tn-01",
    name: "府城毛旅社",
    slug: "tainan-fur-inn",
    city: { name: "台南", slug: "tainan" },
    district: "東區",
    address: "台南市東區崇學路 88 號",
    phone: "06-290-1818",
    lineId: "@furinn",
    googleMapUrl: "https://www.google.com/maps?q=台南市東區崇學路88號&output=embed",
    description: "位於東區生活圈，提供小班制安親、住宿前評估與睡前回報，適合重視細節照護的家庭。",
    priceMin: 700,
    priceMax: 1650,
    rating: 4.9,
    isFeatured: true,
    petTypes: ["狗"],
    sizeLimits: ["小型犬", "中型犬"],
    services: ["寵物住宿", "寵物安親", "24小時監視器"],
    tags: ["小班制", "住宿前評估", "睡前回報"],
    hours: "週一至週日 09:30-21:00",
    images: [imagePool[2], imagePool[0], imagePool[1]].map((url, index) => ({ url, alt: `府城毛旅社照片 ${index + 1}` }))
  },
  {
    id: "tn-02",
    name: "安平日光寵物會館",
    slug: "anping-sun-pet-resort",
    city: { name: "台南", slug: "tainan" },
    district: "安平區",
    address: "台南市安平區健康三街 36 號",
    phone: "06-299-3688",
    lineId: "@sunpet",
    googleMapUrl: "https://www.google.com/maps?q=台南市安平區健康三街36號&output=embed",
    description: "房間採自然採光，提供接送、洗澡美容與長住優惠，假期出遊前可一次安排完整照護。",
    priceMin: 850,
    priceMax: 2100,
    rating: 4.5,
    isFeatured: false,
    petTypes: ["狗", "貓"],
    sizeLimits: ["小型犬", "中型犬", "大型犬"],
    services: ["寵物住宿", "寵物美容", "接送服務"],
    tags: ["自然採光", "長住優惠", "可接大型犬"],
    hours: "週一至週六 09:00-19:30",
    images: [imagePool[3], imagePool[1], imagePool[4]].map((url, index) => ({ url, alt: `安平日光寵物會館照片 ${index + 1}` }))
  },
  {
    id: "tn-03",
    name: "赤崁貓寓",
    slug: "chihkan-cat-lodge",
    city: { name: "台南", slug: "tainan" },
    district: "中西區",
    address: "台南市中西區民權路二段 18 號",
    phone: "06-221-0618",
    lineId: "@chikhancat",
    googleMapUrl: "https://www.google.com/maps?q=台南市中西區民權路二段18號&output=embed",
    description: "專注貓咪住宿，設有垂直跳台、獨立貓房與每日食慾紀錄，讓敏感貓也能慢慢適應。",
    priceMin: 600,
    priceMax: 1300,
    rating: 4.7,
    isFeatured: true,
    petTypes: ["貓"],
    sizeLimits: ["小型犬"],
    services: ["寵物住宿", "24小時監視器"],
    tags: ["貓咪專門", "獨立貓房", "食慾紀錄"],
    hours: "週三至週一 10:00-20:00",
    images: [imagePool[4], imagePool[0], imagePool[2]].map((url, index) => ({ url, alt: `赤崁貓寓照片 ${index + 1}` }))
  },
];

